
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 8;
  public static final int LPAREN = 4;
  public static final int LESS = 26;
  public static final int FOR = 22;
  public static final int MINUS = 3;
  public static final int FLOOR = 11;
  public static final int RPAREN = 5;
  public static final int RANGE = 23;
  public static final int IN = 24;
  public static final int COMMA = 14;
  public static final int CI = 33;
  public static final int MOREEQ = 28;
  public static final int PLUS = 2;
  public static final int LESSEQ = 27;
  public static final int IF = 20;
  public static final int OI = 32;
  public static final int EOF = 0;
  public static final int EQUAL = 6;
  public static final int TRUE = 18;
  public static final int error = 1;
  public static final int EQEQ = 31;
  public static final int NUMBER = 34;
  public static final int MOD = 9;
  public static final int LBRACK = 15;
  public static final int TIMES = 7;
  public static final int COLON = 13;
  public static final int RBRACK = 16;
  public static final int WHILE = 21;
  public static final int FLOAT = 35;
  public static final int STRING = 17;
  public static final int FALSE = 19;
  public static final int LABEL = 12;
  public static final int PRINT = 25;
  public static final int MORE = 29;
  public static final int EXPONENT = 10;
  public static final int NOTEQ = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "LPAREN",
  "RPAREN",
  "EQUAL",
  "TIMES",
  "DIVIDE",
  "MOD",
  "EXPONENT",
  "FLOOR",
  "LABEL",
  "COLON",
  "COMMA",
  "LBRACK",
  "RBRACK",
  "STRING",
  "TRUE",
  "FALSE",
  "IF",
  "WHILE",
  "FOR",
  "RANGE",
  "IN",
  "PRINT",
  "LESS",
  "LESSEQ",
  "MOREEQ",
  "MORE",
  "NOTEQ",
  "EQEQ",
  "OI",
  "CI",
  "NUMBER",
  "FLOAT"
  };
}

